
name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/worchestic
    permissions:
      id-token: write
    steps:
    - name: Install the packaging-related tools
      run: python3 -m pip install build twine
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Build the wheel
      run: python3 -m build
    - name: Sanity check the build
      run: twine check dist/*
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
