name: Python Unittests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
  python_matrix:
    strategy:
        matrix:
            version: ['3.8', '3.9', '3.10', '3.11']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.version }}
    - name: Install test runner (tox/tox-gh-actions)
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
